from PyQt6.QtCore import QObject, pyqtSignal, QThread, QTimer
from PyQt6.QtWidgets import QApplication
from PyQt6.QtGui import QClipboard
from core.translator import is_indonesian_text


class OutboundWorker(QThread):
    finished_translation = pyqtSignal(str, str, str, str)  # original, translated, style, error_msg

    def __init__(self, translator, text, style):
        super().__init__()
        self.translator = translator
        self.text = text
        self.style = style

    def run(self):
        try:
            if hasattr(self.translator, "last_error_detail"):
                self.translator.last_error_detail = None
            translated = self.translator.translate_outbound(self.text, style=self.style)
            err = getattr(self.translator, "last_error_detail", None)
            err_msg = err if (err and (translated == self.text or not translated)) else ""
            self.finished_translation.emit(self.text, translated, self.style, err_msg if err_msg else "")
        except Exception as e:
            self.finished_translation.emit(self.text, self.text, self.style, f"Exception: {e}")


class ClipboardListener(QObject):
    """
    Monitors Windows Clipboard for copied Indonesian text.
    Translates outbound Indonesian text into English (Standard or Slang)
    and updates clipboard with anti-looping safeguards.
    Supports high-reliability background polling and a serial queue to handle fast copying (spam).
    """
    outbound_translated = pyqtSignal(dict)  # Emits {'type': 'OUTBOUND', 'original': str, 'translated': str, 'style': str}

    def __init__(self, translator, config_manager, license_manager=None):
        super().__init__()
        self.translator = translator
        self.config = config_manager
        self.license_manager = license_manager
        self.enabled = self.config.get("enable_clipboard_outbound", True)
        self.last_processed_text = ""
        self.last_translated_text = ""
        self.is_busy = False
        self.pending_item = None
        self.current_worker = None

        # Connect to QApplication clipboard
        self.clipboard = QApplication.clipboard()
        self.clipboard.dataChanged.connect(self.on_clipboard_changed)

        # High-reliability background timer (300ms) for Windows 10/11 non-focused applications
        self.poll_timer = QTimer(self)
        self.poll_timer.setInterval(300)
        self.poll_timer.timeout.connect(self.check_clipboard)
        self.poll_timer.start()

        # Single-shot debounce timer to handle fast clipboard spam
        self.debounce_timer = QTimer(self)
        self.debounce_timer.setSingleShot(True)
        self.debounce_timer.setInterval(100)
        self.debounce_timer.timeout.connect(self.check_clipboard)

    def set_enabled(self, enabled):
        self.enabled = enabled
        if enabled:
            self.poll_timer.start()
        else:
            self.poll_timer.stop()

    def on_clipboard_changed(self):
        """Triggered on native Windows clipboard dataChanged event with 100ms debounce."""
        if not self.enabled:
            return
        self.debounce_timer.start()

    def check_clipboard(self):
        if not self.enabled:
            return

        if self.license_manager and not self.license_manager.is_active():
            return

        try:
            text = self.clipboard.text().strip()
        except Exception:
            return

        if not text or len(text) < 2:
            return

        # Skip if text is the exact output we just wrote to the clipboard
        if text == self.last_translated_text:
            return

        # Skip if text is identical to the last processed text
        if text == self.last_processed_text:
            return

        lower_text = text.lower()
        # Skip URLs, file paths, and screenshot paths
        if lower_text.startswith(("http://", "https://", "file://", "c:\\", "d:\\", "e:\\")):
            self.last_processed_text = text
            self.outbound_translated.emit({
                "type": "OUTBOUND_IGNORED",
                "original": text,
                "reason": "URL / Path File (Diabaikan)"
            })
            return

        # Skip pure system slash commands (except /me and /do roleplay commands)
        if text.startswith("/") and not (lower_text.startswith("/me ") or lower_text.startswith("/do ") or lower_text == "/me" or lower_text == "/do"):
            self.last_processed_text = text
            self.outbound_translated.emit({
                "type": "OUTBOUND_IGNORED",
                "original": text,
                "reason": "Perintah Slash System (Diabaikan)"
            })
            return

        # Anti-looping: Skip if text is already in English / non-Indonesian (e.g. text generated by Voice listener)
        if not is_indonesian_text(text):
            self.last_processed_text = text
            return

        style = self.config.get("outbound_style", "Standard English")

        # Serial Worker Queue: If a worker is currently processing, queue the latest text
        if self.is_busy:
            self.pending_item = (text, style)
            return

        self._start_translation(text, style)

    def _start_translation(self, text, style):
        self.is_busy = True
        self.last_processed_text = text

        if hasattr(self.translator, "log_debug"):
            self.translator.log_debug(f"[Clipboard Outbound Start] Translating: '{text}' (Style: {style})")

        self.current_worker = OutboundWorker(self.translator, text, style)
        self.current_worker.finished_translation.connect(self.on_worker_finished)
        self.current_worker.start()

    def on_worker_finished(self, original, translated, style, error_msg=""):
        self.current_worker = None

        if translated and translated != original and not error_msg:
            self.last_translated_text = translated

            if hasattr(self.translator, "log_debug"):
                self.translator.log_debug(f"[Clipboard Outbound Success] '{original}' -> '{translated}' (Style: {style})")

            # Temporarily disconnect dataChanged signal to avoid self-triggering loop
            try:
                self.clipboard.dataChanged.disconnect(self.on_clipboard_changed)
            except Exception:
                pass

            # Set Qt Clipboard directly with explicit Mode.Clipboard
            self.clipboard.setText(translated, QClipboard.Mode.Clipboard)

            # Reconnect dataChanged signal after brief delay
            QTimer.singleShot(150, lambda: self.clipboard.dataChanged.connect(self.on_clipboard_changed))

            # Emit signal for Overlay UI notification
            self.outbound_translated.emit({
                "type": "OUTBOUND",
                "original": original,
                "translated": translated,
                "style": style,
                "rpd_remaining": self.translator.last_rpd_remaining,
                "rpd_limit": self.translator.last_rpd_limit,
                "rpd_reset": self.translator.last_rpd_reset
            })
        else:
            # Keep self.last_processed_text = original so poll_timer (300ms) will NOT loop on failed/skipped text
            self.last_processed_text = original

            err_detail = error_msg if error_msg else getattr(self.translator, "last_error_detail", "Translation Failed / Rate Limit Exceeded")
            if not err_detail or err_detail == "[Translation Error]":
                err_detail = "Groq API Error / Rate Limit (HTTP 429)"

            if hasattr(self.translator, "log_debug"):
                self.translator.log_debug(f"⚠️ [Clipboard Outbound Error] '{original}' -> {err_detail}")

            # Emit error signal for Overlay UI status & feed card notification
            self.outbound_translated.emit({
                "type": "OUTBOUND",
                "original": original,
                "translated": None,
                "style": style,
                "error": err_detail,
                "rpd_remaining": self.translator.last_rpd_remaining,
                "rpd_limit": self.translator.last_rpd_limit,
                "rpd_reset": self.translator.last_rpd_reset
            })

        self.is_busy = False

        # If user spammed copy while worker was running, automatically process the latest pending item!
        if self.pending_item:
            next_text, next_style = self.pending_item
            self.pending_item = None
            if next_text != self.last_processed_text and next_text != self.last_translated_text:
                QTimer.singleShot(50, lambda: self._start_translation(next_text, next_style))
